(function () {
  "use strict";

  /* ============================================================
     PAGE MANIFEST
     The page list is generated by tools/scan-pages.js, which
     scans assets/img/ so the page count always follows the images
     that are actually present. Covers use fixed filenames:
       assets/img/cover-front.webp
       assets/img/cover-back.webp
     Content pages:
       assets/img/page-NN.webp (sorted numerically)
     ============================================================ */
  var manifest = window.FLIPBOOK_MANIFEST || { pages: [] };
  var contentFiles = manifest.pages || [];

  function pad2(n) { return String(n).padStart(2, "0"); }

  // In single-page 16:9 mode, every asset is an independent page rendered
  // one at a time. No artificial blank spacer pages are needed.
  var PAGES = [];
  PAGES.push({ type: "Cover", title: "Front cover", src: manifest.coverFront });
  contentFiles.forEach(function (file, i) {
    PAGES.push({ type: "Content", title: "Page " + pad2(i + 1), src: file });
  });
  PAGES.push({ type: "Back cover", title: "Back cover", src: manifest.coverBack });

  var bookEl = document.getElementById("book");

  /* ============================================================
     BUILD StPageFlip PAGES (HTML mode)
     Each page is an independent 16:9 widescreen page.
     ============================================================ */
  var pageNodes = PAGES.map(function (page) {
    var p = document.createElement("div");
    var cls = "page";
    if (page.type === "Cover") cls += " is-front-cover";
    else if (page.type === "Back cover") cls += " is-back-cover";
    p.className = cls;
    p.setAttribute("data-page-type", page.type);
    if (page.src) {
      var img = document.createElement("img");
      img.src = page.src;
      img.alt = page.title;
      img.draggable = false;
      p.appendChild(img);
    }
    bookEl.appendChild(p);
    return p;
  });

  /* ============================================================
     INITIALIZE StPageFlip (Single-Page 16:9 Mode)
     ============================================================ */
  var RESERVED_H = 250;      // masthead + hero + meta + toolbar + hint + padding
  var PAGE_RATIO = 16 / 9;   // 16:9 widescreen aspect ratio

  var settings = {
    width: 800,
    height: 450,
    size: "fixed",
    minWidth: 260,
    maxWidth: 1200,
    minHeight: 146,
    maxHeight: 675,
    maxShadowOpacity: 0.25,
    showCover: false,        // Each cover is treated as an individual 16:9 page
    usePortrait: true,       // Enforces single-page reading format across all screen widths
    drawShadow: false,
    flippingTime: 700,
    mobileScrollSupport: false,
    disableFlipByClick: false,
    showPageCorners: false   // disable the corner "peel" hint on hover
  };

  // CSS clamp() equivalent — keeps the page fluid with min/max bounds
  function clamp(v, min, max) { return Math.max(min, Math.min(v, max)); }

  function computePageSize() {
    var vw = window.innerWidth;
    var vh = window.innerHeight;
    var isMobile = window.matchMedia("(max-width: 760px), (pointer: coarse)").matches;

    // Fluid single-page width clamped within viewport bounds
    var maxAvailableW = isMobile ? clamp(vw * 0.86, 260, 600) : clamp(vw * 0.78, 360, 1140);
    var maxAvailableH = clamp(vh - (isMobile ? 260 : RESERVED_H), 180, 680);

    var pageW = maxAvailableW;
    var pageH = pageW / PAGE_RATIO;

    if (pageH > maxAvailableH) {
      pageH = maxAvailableH;
      pageW = pageH * PAGE_RATIO;
    }

    return { width: Math.round(pageW), height: Math.round(pageH) };
  }

  (function initSize() {
    var s = computePageSize();
    settings.width = settings.minWidth = settings.maxWidth = s.width;
    settings.height = settings.minHeight = settings.maxHeight = s.height;
  })();

  var pageFlip = new St.PageFlip(bookEl, settings);
  pageFlip.loadFromHTML(pageNodes);

  // Set all pages to soft density for smooth, consistent page turns
  (function unifyDensity() {
    var count = pageFlip.getPageCount();
    for (var i = 0; i < count; i++) {
      var pg = pageFlip.getPage(i);
      if (pg) {
        pg.setDensity("soft");
        pg.setDrawingDensity("soft");
      }
    }
  })();

  window.addEventListener("resize", function () {
    var s = computePageSize();
    var is = pageFlip.getSettings();
    is.width = is.minWidth = is.maxWidth = s.width;
    is.height = is.minHeight = is.maxHeight = s.height;
    pageFlip.update();
    applyBookTransform();
  });

  /* ============================================================
     READOUT & ZOOM TRANSFORM
     In single-page mode, each 16:9 page is naturally centered.
     ============================================================ */
  var pageReadout = document.getElementById("pageReadout");
  var hint = document.getElementById("hint");
  var zoomLevel = 1;

  function applyBookTransform() {
    var parts = [];
    if (zoomLevel !== 1) {
      parts.push("scale(" + zoomLevel + ")");
    }
    bookEl.style.transform = parts.length ? parts.join(" ") : "";
  }

  function updateMeta() {
    var idx = pageFlip.getCurrentPageIndex();
    var total = pageFlip.getPageCount();
    pageReadout.textContent = pad2(idx + 1) + " / " + pad2(total);

    // highlight current item in TOC
    document.querySelectorAll("#tocList button").forEach(function (btn) {
      btn.setAttribute("aria-current", String(Number(btn.dataset.page) - 1 === idx));
    });
  }

  pageFlip.on("flip", function () {
    updateMeta();
    applyBookTransform();
  });
  pageFlip.on("changeOrientation", function () {
    applyBookTransform();
  });

  /* ============================================================
     TABLE OF CONTENTS (slide-in panel)
     ============================================================ */
  var tocList = document.getElementById("tocList");
  var tocPanel = document.getElementById("tocPanel");
  var tocBackdrop = document.getElementById("tocBackdrop");
  var tocButton = document.getElementById("tocButton");
  var tocClose = document.getElementById("tocClose");

  PAGES.forEach(function (page, i) {
    var li = document.createElement("li");
    var btn = document.createElement("button");
    btn.type = "button";
    btn.dataset.page = String(i + 1);
    var thumb = page.src
      ? '<span class="toc-thumb"><img src="' + page.src + '" alt="" loading="lazy" draggable="false"></span>'
      : '<span class="toc-thumb"></span>';
    btn.innerHTML =
      thumb +
      '<span class="toc-text">' +
        '<span class="toc-title">' + page.title + "</span>" +
      "</span>";
    btn.addEventListener("click", function () {
      pageFlip.flip(i);
      closeToc();
    });
    li.appendChild(btn);
    tocList.appendChild(li);
  });

  function openToc() {
    tocPanel.hidden = false;
    tocBackdrop.hidden = false;
    requestAnimationFrame(function () {
      tocPanel.classList.add("open");
      tocBackdrop.classList.add("open");
    });
    tocButton.setAttribute("aria-expanded", "true");
  }
  function closeToc() {
    tocPanel.classList.remove("open");
    tocBackdrop.classList.remove("open");
    tocButton.setAttribute("aria-expanded", "false");
    setTimeout(function () {
      if (!tocPanel.classList.contains("open")) {
        tocPanel.hidden = true;
        tocBackdrop.hidden = true;
      }
    }, 260);
  }

  tocButton.addEventListener("click", function () {
    tocPanel.hidden ? openToc() : closeToc();
  });
  tocClose.addEventListener("click", closeToc);
  tocBackdrop.addEventListener("click", closeToc);

  /* ============================================================
     NAVIGATION (Page-by-page)
     ============================================================ */
  var nextBtn = document.getElementById("nextButton");
  var prevBtn = document.getElementById("prevButton");

  if (nextBtn) {
    nextBtn.addEventListener("click", function () {
      pageFlip.flipNext("top");
      hideHint();
    });
  }
  if (prevBtn) {
    prevBtn.addEventListener("click", function () {
      pageFlip.flipPrev("bottom");
      hideHint();
    });
  }

  function hideHint() {
    if (hint) hint.classList.add("gone");
  }

  window.addEventListener("keydown", function (e) {
    if (e.key === "ArrowRight") { pageFlip.flipNext("top"); hideHint(); }
    else if (e.key === "ArrowLeft") { pageFlip.flipPrev("bottom"); hideHint(); }
    else if (e.key === "+" || e.key === "=") setZoom(zoomLevel * 1.2);
    else if (e.key === "-") setZoom(zoomLevel / 1.2);
    else if (e.key.toLowerCase() === "f") {
      var fsBtn = document.getElementById("fullscreenButton");
      if (fsBtn) fsBtn.click();
    }
    else if (e.key === "Escape") closeToc();
  });

  /* ============================================================
     ZOOM
     ============================================================ */
  var zoomReadout = document.getElementById("zoomReadout");
  var zoomOutButton = document.getElementById("zoomOut");
  var zoomInButton = document.getElementById("zoomIn");

  function setZoom(z) {
    zoomLevel = Math.max(0.9, Math.min(1.6, z));
    if (zoomReadout) zoomReadout.textContent = Math.round(zoomLevel * 100) + "%";
    if (zoomOutButton) zoomOutButton.disabled = zoomLevel <= 0.91;
    if (zoomInButton) zoomInButton.disabled = zoomLevel >= 1.59;
    applyBookTransform();
  }

  if (zoomInButton) zoomInButton.addEventListener("click", function () { setZoom(zoomLevel * 1.2); });
  if (zoomOutButton) zoomOutButton.addEventListener("click", function () { setZoom(zoomLevel / 1.2); });

  /* ============================================================
     FULLSCREEN
     ============================================================ */
  var fsBtn = document.getElementById("fullscreenButton");
  var bookWrap = document.getElementById("bookWrap");

  if (fsBtn && bookWrap) {
    fsBtn.addEventListener("click", function () {
      if (!document.fullscreenElement && !document.webkitFullscreenElement) {
        if (bookWrap.requestFullscreen) bookWrap.requestFullscreen();
        else if (bookWrap.webkitRequestFullscreen) bookWrap.webkitRequestFullscreen();
      } else {
        if (document.exitFullscreen) document.exitFullscreen();
        else if (document.webkitExitFullscreen) document.webkitExitFullscreen();
      }
    });

    var onFsChange = function () {
      var isFs = !!(document.fullscreenElement || document.webkitFullscreenElement);
      fsBtn.setAttribute("aria-pressed", String(isFs));
      setTimeout(function () {
        var s = computePageSize();
        var is = pageFlip.getSettings();
        is.width = is.minWidth = is.maxWidth = s.width;
        is.height = is.minHeight = is.maxHeight = s.height;
        pageFlip.update();
        applyBookTransform();
      }, 100);
    };

    document.addEventListener("fullscreenchange", onFsChange);
    document.addEventListener("webkitfullscreenchange", onFsChange);
  }

  // Initial metadata update
  updateMeta();
})();
