(function () {
  "use strict";

  /* ============================================================
     PAGE MANIFEST
     The page list is generated by tools/scan-pages.py, which
     scans assets/img/ so the page count always follows the images
     that are actually present. Covers use fixed filenames:
       assets/img/cover-front.webp
       assets/img/cover-back.webp
     Content pages:
       assets/img/page-NNN.webp (sorted numerically)
     ============================================================ */
  var manifest = window.FLIPBOOK_MANIFEST || { pages: [] };
  var contentFiles = manifest.pages || [];

  // Blank pages are inserted automatically so the back cover always
  // closes over empty space (never over a content page):
  //   even number of content pages -> 2 blanks (last page sits on the right)
  //   odd  number of content pages -> 1 blank  (last page sits on the left)
  var blankCount = contentFiles.length % 2 === 0 ? 2 : 1;

  function pad2(n) { return String(n).padStart(2, "0"); }

  var PAGES = [];
  PAGES.push({ type: "Cover", title: "Front cover", src: manifest.coverFront });
  contentFiles.forEach(function (file, i) {
    PAGES.push({ type: "Content", title: "Page " + pad2(i + 1), src: file });
  });
  for (var b = 0; b < blankCount; b++) {
    PAGES.push({ type: "Blank", title: "", src: null });
  }
  PAGES.push({ type: "Back cover", title: "Back cover", src: manifest.coverBack });

  // Keep the "contents" section heading in sync with the real page count.
  var contentsTitle = document.getElementById("contents-title");
  if (contentsTitle) {
    contentsTitle.textContent = contentFiles.length + " pages, one continuous story.";
  }

  var bookEl = document.getElementById("book");

  /* ============================================================
     BUILD StPageFlip PAGES (HTML mode)
     Blank pages render as plain paper (no image).
     ============================================================ */
  var pageNodes = PAGES.map(function (page) {
    var p = document.createElement("div");
    var cls = "page";
    if (page.type === "Cover") cls += " is-front-cover";
    else if (page.type === "Back cover") cls += " is-back-cover";
    else if (page.type === "Blank") cls += " is-blank";
    p.className = cls;
    p.setAttribute("data-page-type", page.type);
    if (page.src) {
      var img = document.createElement("img");
      img.src = page.src;
      img.alt = page.title;
      img.draggable = false;
      p.appendChild(img);
    }
    bookEl.appendChild(p);
    return p;
  });

  /* ============================================================
     INITIALIZE StPageFlip
     ============================================================ */
  var RESERVED_H = 310;          // hero copy + meta + toolbar + hint + padding
  var PAGE_RATIO = 2481 / 3508;  // portrait page aspect ratio

  var settings = {
    width: 550,
    height: 778,
    size: "fixed",
    minWidth: 220,
    maxWidth: 1000,
    minHeight: 240,
    maxHeight: 1273,
    maxShadowOpacity: 0.3,
    showCover: true,
    usePortrait: true,
    drawShadow: false,
    flippingTime: 900,
    mobileScrollSupport: false,
    disableFlipByClick: false,
    showPageCorners: false   // disable the corner "peel" hint on hover
  };

  // CSS clamp() equivalent — keeps the book fluid with min/max bounds
  function clamp(v, min, max) { return Math.max(min, Math.min(v, max)); }

  function computePageSize() {
    var vw = window.innerWidth;
    var vh = window.innerHeight;
    var isMobile = window.matchMedia("(max-width: 760px), (pointer: coarse)").matches;

    if (isMobile) {
      // single page fills the width fluidly (clamped); 82vw leaves room for the side arrows
      var pageW = clamp(vw * 0.82, 220, 620);
      var pageH = pageW / PAGE_RATIO;
      var maxH = clamp(vh - 400, 300, 900);
      if (pageH > maxH) {
        pageH = maxH;
        pageW = pageH * PAGE_RATIO;
      }
      return { width: Math.round(pageW), height: Math.round(pageH) };
    }

    // desktop spread: fluid page width, clamped by width + height
    var pageW = clamp(vw * 0.30, 240, 520);
    var pageH = pageW / PAGE_RATIO;
    var availH = clamp(vh - RESERVED_H, 300, 900);
    if (pageH > availH) {
      pageH = availH;
      pageW = pageH * PAGE_RATIO;
    }
    return { width: Math.round(pageW), height: Math.round(pageH) };
  }

  (function initSize() {
    var s = computePageSize();
    settings.width = settings.minWidth = settings.maxWidth = s.width;
    settings.height = settings.minHeight = settings.maxHeight = s.height;
  })();

  var pageFlip = new St.PageFlip(bookEl, settings);
  pageFlip.loadFromHTML(pageNodes);

  // StPageFlip's createSpread() forces the first and last pages (the covers)
  // to "hard" density (thick board). Reset them to "soft" so every page flips
  // like thin, smooth paper.
  (function unifyDensity() {
    var first = pageFlip.getPage(0);
    var last = pageFlip.getPage(pageFlip.getPageCount() - 1);
    [first, last].forEach(function (pg) {
      pg.setDensity("soft");
      pg.setDrawingDensity("soft");
    });
  })();

  window.addEventListener("resize", function () {
    var s = computePageSize();
    var is = pageFlip.getSettings();
    is.width = is.minWidth = is.maxWidth = s.width;
    is.height = is.minHeight = is.maxHeight = s.height;
    pageFlip.update();
    applyBookTransform();
  });

  /* ============================================================
     READOUT + COVER CENTERING
     ============================================================ */
  var pageReadout = document.getElementById("pageReadout");
  var hint = document.getElementById("hint");

  var zoomLevel = 1;

  function applyBookTransform() {
    var idx = pageFlip.getCurrentPageIndex();
    var total = pageFlip.getPageCount();
    var parts = [];

    // center the front / back cover when it is shown alone (single page)
    var isSingle = (idx === 0) || (idx === total - 1);
    if (isSingle && pageFlip.getOrientation() === "landscape") {
      var offset = bookEl.offsetWidth / 4;
      var dir = (idx === 0) ? -1 : 1;
      parts.push("translateX(" + (dir * offset) + "px)");
    }
    if (zoomLevel !== 1) {
      parts.push("scale(" + zoomLevel + ")");
    }
    bookEl.style.transform = parts.join(" ");
  }

  function updateMeta() {
    var idx = pageFlip.getCurrentPageIndex();
    var total = pageFlip.getPageCount();
    pageReadout.textContent = pad2(idx + 1) + " / " + pad2(total);

    // highlight current item in TOC + contents grid
    document.querySelectorAll("#tocList button, #contentsGrid button").forEach(function (btn) {
      btn.setAttribute("aria-current", String(Number(btn.dataset.page) - 1 === idx));
    });
  }

  pageFlip.on("flip", function () {
    updateMeta();
    applyBookTransform();
  });
  pageFlip.on("changeOrientation", function () {
    applyBookTransform();
  });

  /* ============================================================
     TABLE OF CONTENTS (slide-in panel)
     Blank pages are omitted — they are structural spacers, not
     readable sections.
     ============================================================ */
  var tocList = document.getElementById("tocList");
  var tocPanel = document.getElementById("tocPanel");
  var tocBackdrop = document.getElementById("tocBackdrop");
  var tocButton = document.getElementById("tocButton");
  var tocClose = document.getElementById("tocClose");

  PAGES.forEach(function (page, i) {
    if (page.type === "Blank") return;
    var li = document.createElement("li");
    var btn = document.createElement("button");
    btn.type = "button";
    btn.dataset.page = String(i + 1);
    var thumb = page.src
      ? '<span class="toc-thumb"><img src="' + page.src + '" alt="" loading="lazy" draggable="false"></span>'
      : '<span class="toc-thumb"></span>';
    btn.innerHTML =
      thumb +
      '<span class="toc-text">' +
        '<span class="toc-title">' + page.title + "</span>" +
      "</span>";
    btn.addEventListener("click", function () {
      pageFlip.flip(i);
      closeToc();
    });
    li.appendChild(btn);
    tocList.appendChild(li);
  });

  function openToc() {
    tocPanel.hidden = false;
    tocBackdrop.hidden = false;
    requestAnimationFrame(function () {
      tocPanel.classList.add("open");
      tocBackdrop.classList.add("open");
    });
    tocButton.setAttribute("aria-expanded", "true");
  }
  function closeToc() {
    tocPanel.classList.remove("open");
    tocBackdrop.classList.remove("open");
    tocButton.setAttribute("aria-expanded", "false");
    setTimeout(function () {
      if (!tocPanel.classList.contains("open")) {
        tocPanel.hidden = true;
        tocBackdrop.hidden = true;
      }
    }, 260);
  }

  tocButton.addEventListener("click", function () {
    tocPanel.hidden ? openToc() : closeToc();
  });
  tocClose.addEventListener("click", closeToc);
  tocBackdrop.addEventListener("click", closeToc);

  /* ============================================================
     CONTENTS GRID (page section)
     ============================================================ */
  var contentsGrid = document.getElementById("contentsGrid");
  PAGES.forEach(function (page, i) {
    if (page.type === "Blank") return;
    var li = document.createElement("li");
    var btn = document.createElement("button");
    btn.type = "button";
    btn.dataset.page = String(i + 1);
    var typeLabel = page.type === "Content" ? "Content" : "Cover";
    btn.innerHTML =
      '<span class="contents-title">' + page.title + "</span>" +
      '<span class="contents-type">' + typeLabel + "</span>";
    btn.addEventListener("click", function () {
      pageFlip.flip(i);
      document.getElementById("flipbook").scrollIntoView({ behavior: "smooth", block: "center" });
    });
    li.appendChild(btn);
    contentsGrid.appendChild(li);
  });

  /* ============================================================
     NAVIGATION
     ============================================================ */
  document.getElementById("nextButton").addEventListener("click", function () {
    pageFlip.flipNext("top");
    hideHint();
  });
  document.getElementById("prevButton").addEventListener("click", function () {
    pageFlip.flipPrev("bottom");
    hideHint();
  });

  function hideHint() {
    hint.classList.add("gone");
  }

  window.addEventListener("keydown", function (e) {
    if (e.key === "ArrowRight") { pageFlip.flipNext("top"); hideHint(); }
    else if (e.key === "ArrowLeft") { pageFlip.flipPrev("bottom"); hideHint(); }
    else if (e.key === "+" || e.key === "=") setZoom(zoomLevel * 1.2);
    else if (e.key === "-") setZoom(zoomLevel / 1.2);
    else if (e.key.toLowerCase() === "f") document.getElementById("fullscreenButton").click();
    else if (e.key === "Escape") closeToc();
  });

  /* ============================================================
     ZOOM
     ============================================================ */
  var zoomReadout = document.getElementById("zoomReadout");
  var zoomOutButton = document.getElementById("zoomOut");
  var zoomInButton = document.getElementById("zoomIn");

  function setZoom(z) {
    zoomLevel = Math.max(0.9, Math.min(1.6, z));
    zoomReadout.textContent = Math.round(zoomLevel * 100) + "%";
    zoomOutButton.disabled = zoomLevel <= 0.91;
    zoomInButton.disabled = zoomLevel >= 1.59;
    applyBookTransform();
  }

  zoomInButton.addEventListener("click", function () { setZoom(zoomLevel * 1.2); });
  zoomOutButton.addEventListener("click", function () { setZoom(zoomLevel / 1.2); });

  /* ============================================================
     FULLSCREEN
     ============================================================ */
  var fullscreenButton = document.getElementById("fullscreenButton");
  fullscreenButton.addEventListener("click", function () {
    if (!document.fullscreenElement) {
      document.getElementById("bookWrap").requestFullscreen().catch(function () {});
    } else {
      document.exitFullscreen();
    }
  });
  document.addEventListener("fullscreenchange", function () {
    fullscreenButton.setAttribute("aria-pressed", String(!!document.fullscreenElement));
    setTimeout(applyBookTransform, 60);
  });

  updateMeta();
  applyBookTransform();
})();
