// AUTO-GENERATED by tools/scan-pages.js — do not edit by hand.
window.FLIPBOOK_MANIFEST = {
  coverFront: "assets/img/cover-front.webp",
  coverBack: "assets/img/cover-back.webp",
  pages: [
    "assets/img/page-001.webp",
    "assets/img/page-002.webp",
    "assets/img/page-003.webp",
    "assets/img/page-004.webp",
    "assets/img/page-005.webp",
    "assets/img/page-006.webp",
    "assets/img/page-007.webp",
    "assets/img/page-008.webp",
    "assets/img/page-009.webp",
    "assets/img/page-010.webp",
  ]
};
