// AUTO-GENERATED by tools/scan-pages.js — do not edit by hand.
window.FLIPBOOK_MANIFEST = {
  coverFront: "assets/img/cover-front.webp",
  coverBack: "assets/img/cover-back.webp",
  pages: [
    "assets/img/page-01.webp",
    "assets/img/page-02.webp",
    "assets/img/page-03.webp",
    "assets/img/page-04.webp",
    "assets/img/page-05.webp",
    "assets/img/page-06.webp",
    "assets/img/page-07.webp",
    "assets/img/page-08.webp",
    "assets/img/page-09.webp",
    "assets/img/page-10.webp",
  ]
};
