import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..');
const IMG_DIR = path.join(ROOT, 'assets', 'img');
const OUT = path.join(ROOT, 'js', 'pages.js');

const COVER_FRONT = 'cover-front.webp';
const COVER_BACK = 'cover-back.webp';
const PAGE_RE = /^page-(\d+)\.webp$/;

function main() {
  if (!fs.existsSync(IMG_DIR)) {
    console.error(`Images directory not found: ${IMG_DIR}`);
    process.exit(1);
  }

  const files = fs.readdirSync(IMG_DIR);
  const pages = [];
  for (const name of files) {
    const m = PAGE_RE.exec(name);
    if (m) {
      pages.push([parseInt(m[1], 10), name]);
    }
  }
  pages.sort((a, b) => a[0] - b[0]);

  const lines = [
    '// AUTO-GENERATED by tools/scan-pages.js — do not edit by hand.',
    'window.FLIPBOOK_MANIFEST = {',
    `  coverFront: "assets/img/${COVER_FRONT}",`,
    `  coverBack: "assets/img/${COVER_BACK}",`,
    '  pages: [',
  ];
  for (const [, filename] of pages) {
    lines.push(`    "assets/img/${filename}",`);
  }
  lines.push('  ]');
  lines.push('};');
  lines.push('');

  fs.writeFileSync(OUT, lines.join('\n'), 'utf-8');
  console.log(`Generated ${path.relative(ROOT, OUT)} with ${pages.length} content page(s).`);
}

main();
