#!/usr/bin/env python3
"""Scan assets/img/ and generate the flipbook page manifest (js/pages.js).

Usage:
    python3 tools/scan-pages.py

It looks for:
    assets/img/cover-front.webp   -> front cover
    assets/img/cover-back.webp    -> back cover
    assets/img/page-NNN.webp      -> content pages (sorted numerically)

The generated js/pages.js is read by js/main.js, so the page count always
follows the images that are actually present — no manual editing needed.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
IMG_DIR = ROOT / "assets" / "img"
OUT = ROOT / "js" / "pages.js"

COVER_FRONT = "cover-front.webp"
COVER_BACK = "cover-back.webp"
PAGE_RE = re.compile(r"^page-(\d+)\.webp$")


def main() -> None:
    if not IMG_DIR.is_dir():
        raise SystemExit(f"images folder not found: {IMG_DIR}")

    pages = []
    for name in sorted(IMG_DIR.iterdir()):
        m = PAGE_RE.match(name.name)
        if m:
            pages.append((int(m.group(1)), name.name))
    pages.sort(key=lambda item: item[0])

    warnings = []
    if not (IMG_DIR / COVER_FRONT).exists():
        warnings.append(f"missing {COVER_FRONT}")
    if not (IMG_DIR / COVER_BACK).exists():
        warnings.append(f"missing {COVER_BACK}")
    if not pages:
        warnings.append("no page-NNN.webp found")

    lines = [
        "// AUTO-GENERATED by tools/scan-pages.py — do not edit by hand.",
        "window.FLIPBOOK_MANIFEST = {",
        f'  coverFront: "assets/img/{COVER_FRONT}",',
        f'  coverBack: "assets/img/{COVER_BACK}",',
        "  pages: [",
    ]
    for _, filename in pages:
        lines.append(f'    "assets/img/{filename}",')
    lines.append("  ]")
    lines.append("};")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"Generated {OUT.relative_to(ROOT)} with {len(pages)} content page(s).")
    for w in warnings:
        print(f"WARNING: {w}")


if __name__ == "__main__":
    main()
